### ISSUE TITLE
Breaking computer interface in rare(?) cases

### ISSUE THREAD

**Issue by gizmogoat** [Ivy2345/GripMonke#1]
Unsure if this is a widespread issue.

**Comment by AHauntedArmy** [comment]
i had the same issue with my pc version of antitagcheat, computer interface removes the mod entry from the list if ondisable is implemented and activated from the mod status view, but doesn't update the index values so they're offset. re-enabling the mod would put everything back to normal so i opted to not implement onenable and ondisable and control it through its view instead.

**Comment by gizmogoat** [comment]
I'll keep this in mind for future revisions/mods, although this is no longer an issue as the view is gone anyway
